### PR TITLE
IpConfigurator: Add UI Skeleton Code

### PR DESCRIPTION
**Pull request by skyler-rs**
> ### Motivate of the pull request
> - [ ] This Implements milestone 2 of the IpConfigurator feature

> ### Describe the technical details
> #### What is currently done? (Provide issue link if applicable)
> 
> 
> 
> 
> 
>
> #### What does this pull request change?
> - [ ] Updates stub files to contain basic, initial implementations of the gui skeleton to provide stakeholders with a more realistic look of the future UI.
> - [ ] The IP configurator UI is now instantiated and added to our existing left dock widget tabs, but it is hidden by default. The UI can be shown with ipconfigurator_show
> - [ ] Fixes a small typo in main_window.cpp: taskDocWidget -> taskDockWidget
> - [ ] Changes tcl command from ipconfigurator_close to ipconfigurator_hide to more accurately represent what happens

> ### Which part of the code base require a change
> 
> - [ ] UI
> - [ ] Regression tests (small naming update)

> ### Impact of the pull request
> - [ ] UI now instantiates (and hides) the IpConfigurator DockWidget/Tab

> ### Testing
> - [ ] This uses the existing gui_ipconfigurator.tcl test to ensure the IpConfigurator UI skeleton can be built and instantiated
> - [ ] The config dialog is not currently tested as our tcl harness currently doesn't allow for the control of dialogs and this is a modal dialog so it would hang the test if shown currently.
> - [ ] No gui component testing is done because this is skeleton code that will change in future milestones and we don't have the tcl harness for it

> ### UI Changes
image
image

### CODE REVIEW

**Comment by skyler-rs** [comment]
Leaving this as a draft PR for now in-case i need to do any merges etc once the Milestone 1 PR of the IpConfigurator is merged into main.

**Review by ravic-rs — COMMENTED** [review]
Pending UI changes after initial review with team.

**Comment by skyler-rs** [comment]
Per a UI review, the IP tab has been moved to the right dock widget area. IP instances have been hidden for now as I won't know how they will integrate with the source tab until i start implementing milestones 3&4
image

**Review by ravic-rs — APPROVED** [review]
Looks good.

**Pull request merged**
