### PR TITLE
[GEMINIEDA-461] Adding View Log option to task view context menu

### PR DESCRIPTION
**Pull request by skyler-rs**
> ### Motivate of the pull request
> - [x] To address an existing issue. If so, please provide a link to the issue: [GEMINIEDA-461]
> - [ ] Breaking new feature. If so, please describe details in the description part.

> ### Describe the technical details
> #### What is currently done? (Provide issue link if applicable)
> - logs were output to the project dir w/ no ui interface besides Open File
> - Synthesis log was saved as <project_name>_synth.log
> - Packing, Placement, Routing, Timing Anaylsis, & Power Analysis task all logged into vpr_stdout.log
>
> ### What does this pull request change?
> - Task view context menu now has a "View <task> Log" option in the context menu
image
> - Logic has been added to disable the view log option if a log file doesn't exist
image
> - In Foedag
>   - all tasks log to a dummy file in the project dir, for example `<project_dir>/synthesis.rpt`
> - In Raptor
>   - Packing, Placement, Routing, Timing Anaylsis, & Power Analysis now have logic to copy their vpr_stdout.log results to `<task_name>.rpt`

> ### Note for Stakeholders
> - In Raptor, the following tasks don't seem to have log files currently. Please let me know if they exist and I will add them: IP Generate, Analysis, Global Placement, Bitstream

> ### Which part of the code base require a change
> 
> - [x] Library: Compiler, Main
> - [ ] Plug-in: <Specify the plugin name>
> - [ ] Engine
> - [ ] Documentation
> - [ ] Regression tests
> - [ ] Continous Integration (CI) scripts

> ### Testing
> Manually tested in foedag and raptor

### CODE REVIEW

**Review by ravic-rs — COMMENTED** [review]
It appears we will still end up with a vpr std out log, correct ?

**Comment by skyler-rs** [comment]
@ravic-rs Yep, the code makes a copy of vpr_stdout.log at the end of each task that uses vpr so no changes have been made to the original vpr_stdout.log.

**Comment by ravic-rs** [comment]
> @ravic-rs Yep, the code makes a copy of vpr_stdout.log at the end of each task that uses vpr so no changes have been made to the original vpr_stdout.log.

Thanks. I was thinking there is a way to add new file for each step. Also we have some missing rpt for other tasks you described.
Let's wait for Alain's thoughts. I think we should merge with rpt files we have now.

**Comment by alaindargelas** [comment]
Yes, merge with what we have.
Copy the files, don't try to force VPR to rename the file.

**Review by ravic-rs — APPROVED** [review]
Looks good.

**Pull request merged**
