### PR TITLE
[RG-88] Remove Raptor specific synthesis settings

### PR DESCRIPTION
**Pull request by skyler-rs**
> ### Motivate of the pull request
> - [x] To address an existing issue. If so, please provide a link to the issue: RG-88

> ### Describe the technical details
> #### What is currently done? (Provide issue link if applicable)
> Foedag's settings file has settings specific to Raptor
>
> #### What does this pull request change?
> Effort, FSM Encoding, Carry, and Fast Synthesis options have been removed from the Synthesis settings
image

> ### Which part of the code base require a change
> 
> - [x] Library: Main
> - [ ] Plug-in: <Specify the plugin name>
> - [ ] Engine
> - [ ] Documentation
> - [ ] Regression tests
> - [ ] Continous Integration (CI) scripts

> ### Impact of the pull request
> - [ ] Require a change on Quality of Results (QoR)
> - [ ] Break back-compatibility. If so, please list who may be influenced.
> - [x] None

> Testing
> - This is a meta file change only, no actual code has changed and the file is only used by foedag (Foedag_rs and Raptor have their own copies of the file). No testing has been done other than manually verifying that the requested fields have been removed from foedag.

### CODE REVIEW

**Comment by KochynVolodymyr** [comment]
Did you test on raptor?

**Comment by skyler-rs** [comment]
> Did you test on raptor?

See "Testing" in description, this file doesn't get used by Raptor or Foedag_rs so there's not real changes to down stream with this.

**Comment by skyler-rs** [comment]
Converting PR to draft, sounds like there are backend changes required as well that will require some research.

**Comment by ravic-rs** [comment]
Will the backend break if we make this change ?
I’m trying to figure the reason to wait.
________________________________

**Comment by skyler-rs** [comment]
> Will the backend break if we make this change ? I’m trying to figure the reason to wait.

It won't break anything, but it sounds like the original request wanted back end changes as well.

**Comment by skyler-rs** [comment]
Gotcha, I've re-opened this PR for review/merge. Just to clarify this will only remove the listed options from the FOEDAG synthesis settings UI, nothing else will change currently.

**Review by alain-rs — APPROVED** [review]

**Pull request merged**
