### PR TITLE
[EDA-1062] Pin planner updates: replace pin name with ball name and add possibility to use ball ids

### PR DESCRIPTION
**Pull request by KochynVolodymyr**
### Motivate of the pull request
 - [ ] To address an existing issue. If so, please provide a link to the issue: <issue id>
 - [x] Breaking new feature. If so, please describe details in the description part.

### Describe the technical details
Package pin name will use Ball name or Ball id instead of Bump/Pin name:
image

Allow user to select use ball name or ball id for the package pin name:
image

*.pin constaint file supports both notation. Before data load to pin planner, there is extra step that converts all data to ball ids or ball names depends on user selection.

 ### Which part of the code base require a change
 
 - [x] Library: foedagcore, pinassignment
 - [ ] Plug-in: <Specify the plugin name>
 - [ ] Engine
 - [ ] Documentation
 - [ ] Regression tests
 - [ ] Continous Integration (CI) scripts

### CODE REVIEW

**Review by ravic-rs — CHANGES_REQUESTED** [review]
Updates needed:
1. Change names in dialog box.
2. Parsing and PP table generation update to accommodate mixing of both ball names and ball id while manually providing the pin file.

**Comment by KochynVolodymyr** [comment]
@ravic-rs ready

**Comment by alaindargelas** [comment]
How do we access this menu?
https://user-images.githubusercontent.com/95262932/214048860-c42c3001-7f4a-4ae3-97c1-2ee6a21d7bc4.png

**Comment by ravic-rs** [comment]
> How do we access this menu?
> 
> https://user-images.githubusercontent.com/95262932/214048860-c42c3001-7f4a-4ae3-97c1-2ee6a21d7bc4.png

File-Preferences-Pin planner pin selection

**Pull request merged**
