### PR TITLE
Enhance pin location constraint by following "pin_loc_assign_method"

### PR DESCRIPTION
**Pull request by taoli4rs**
command.

> ### Motivate of the pull request
> - [ ] To address an existing issue. If so, please provide a link to the issue: <issue id>
> - [ ] Breaking new feature. If so, please describe details in the description part.
> - [X] Enhance pin location constraint by following "pin_loc_assign_method" command.

> ### Describe the technical details
> #### What is currently done? (Provide issue link if applicable)
> 
> 
> 
> 
> 
> - [X] Currently there is no way in Raptor to allow user to configure pin location assignment method
>
> #### What does this pull request change?
> 
> 
> 
> 
> 
> - [X] This PR is based on UI team's work (where a command "pin_loc_assign_method" had been implemented) to allow pin_c to assign legal pins to un-constrained design ports by following the method specified there by user (though command line or GUI).

> ### Which part of the code base require a change
> 
> - [ ] Library: <Specify the library name>
> - [ ] Plug-in: <Specify the plugin name>
> - [ ] Engine
> - [ ] Documentation
> - [ ] Regression tests
> - [ ] Continous Integration (CI) scripts
> - [X] Pin location constrain

> ### Impact of the pull request

> - [ ] Require a change on Quality of Results (QoR)
> - [ ] Break back-compatibility. If so, please list who may be influenced.
> - [X] No negative impact. This is a new feature.

### CODE REVIEW

**Comment by alain-rs** [comment]
@taoli4rs, please reformat your code:
.github/bin/run-clang-format.sh

**Comment by ravic-rs** [comment]
@taoli4rs we [added a test here](https://github.com/os-fpga/FOEDAG/blob/main/tests/TestBatch/test_compiler_batch.tcl#L21).
 If you think more testcases are needed let me know.

**Comment by taoli4rs** [comment]
>

**Review by ravic-rs — APPROVED** [review]
clang format was fixed, looks good,

**Pull request merged**
