### PR TITLE
Structure existing unit tests; Rename them according to agreed naming conventions.

### PR DESCRIPTION
**Pull request by TarasSydor**
Given commit doesn't add anything new. It just puts existing unit tests under agreed folder structure and naming conventions.

Changes:
- Command_test.cpp was moved to tests/unittest/Command;
- HelloTcl_test.cpp removed to TclInterpreter_test.cpp and moved to tests/unittest/Tcl;
- CMakeLists test registration updated according to new location.

Updating includes appeared to be needless.

### CODE REVIEW

**Comment by ravic-rs** [comment]
Removing the link from description as it's internal.

**Comment by ravic-rs** [comment]
@TarasSydor please change the title. It takes the latest commit message if not edited while creating the PR.

Will you be adding a PR for Utils tests separately?

**Review by skyler-rs — APPROVED** [review]
Changes look good

**Comment by TarasSydor** [comment]
> @TarasSydor please change the title. It takes the latest commit message if not edited while creating the PR.
> 
> Will you be adding a PR for Utils tests separately?

Yes. The next step will be to create a project for unit tests (including new CMakeLists.txt file for it) and to add more tests.

**Pull request merged**
