### PR TITLE
Add a newproject GUI

### PR DESCRIPTION
**Pull request by liibin**
> ### Motivate of the pull request
> - [ ] To address an existing issue. If so, please provide a link to the issue: <issue id>
> - [x ] Breaking new feature. If so, please describe details in the description part.

> ### Describe the technical details
> #### What is currently done? (Provide issue link if applicable) #77 
> 
> 
> 
> 
> 
>
> #### What does this pull request change?
> 
> 
> This PR improves in the following aspects:
menu

> 
> 

> ### Which part of the code base require a change
> 
> - [ ] Library: <Specify the library name>
> - [ ] Plug-in: <Specify the plugin name>
> - [x ] Engine
> - [ ] Documentation
> - [ ] Regression tests
> - [ ] Continous Integration (CI) scripts

> ### Impact of the pull request

> - [ ] Require a change on Quality of Results (QoR)
> - [ ] Break back-compatibility. If so, please list who may be influenced.

### CODE REVIEW

**Comment by tangxifan** [comment]
@liibin I will review the code by this Friday. Can you look into the CI failures? It is mainly about some unit tests and installation problems. We can do it in parallel.

**Comment by alain-rs** [comment]
For the install to work, you need to add the new library to the list of libraries:
https://github.com/os-fpga/FOEDAG/blob/06de346c704632512cbb3307eeacc700b867b5f3/tests/TestInstall/CMakeLists.txt#L141

**Comment by alain-rs** [comment]
You need to add the library to the INSTALL libraries in the top level CMakeFileLists.txt too.

https://github.com/os-fpga/FOEDAG/blob/06de346c704632512cbb3307eeacc700b867b5f3/CMakeLists.txt#L385

**Comment by alain-rs** [comment]
You need to install the lib too, you just installed the header file.

**Review by alain-rs — APPROVED** [review]

**Comment by alain-rs** [comment]
TODO: Create the Tcl commands for this widget and regression test.

**Pull request merged**
