### PR TITLE
msys2 mingw64 build support

### PR DESCRIPTION
**Pull request by coolbreeze413**
> ### Motivate of the pull request
> - [x] To address an existing issue. If so, please provide a link to the issue: <issue id>
Add support for build all the components under Windows with MSYS2 + MinGW64
> - [ ] Breaking new feature. If so, please describe details in the description part.

> ### Describe the technical details
> #### What is currently done? (Provide issue link if applicable)
> 
> 
> 
> 
> 
>
> #### What does this pull request change?
> 
> 
> 
> 
> 

> ### Which part of the code base require a change
> 
> - [ ] Library: <Specify the library name>
> - [ ] Plug-in: <Specify the plugin name>
> - [ ] Engine
> - [ ] Documentation
> - [ ] Regression tests
> - [ ] Continous Integration (CI) scripts

> ### Impact of the pull request

> - [ ] Require a change on Quality of Results (QoR)
> - [ ] Break back-compatibility. If so, please list who may be influenced.

The MSYS2 MinGW64 env is assumed to be setup, and has the following packages installed:
```
pacman -S --needed base-devel mingw-w64-x86_64-toolchain git mingw-w64-x86_64-cmake mingw-w64-x86_64-qt5-base-debug mingw-w64-x86_64-qt5 mingw-w64-x86_64-swig mingw-w64-x86_64-qt5-declarative-debug mingw-w64-x86_64-tcl mingw-w64-x86_64-zlib
```

### CODE REVIEW

**Review by alain-rs — APPROVED** [review]

**Comment by coolbreeze413** [comment]
fixed issues with testinstall in msys2 mingw64 env, and cleaned up msys2 ci steps. Now, it looks clean for msys2.

msvc build seems to be having issues, but looks unrelated to these changes, as it has been failing at the same place for previous few CI runs as well. (copying built tcl lib) - most likely the path from which the copy is being attempted is not valid, probably due to changes in the windows-2022 gh container msvc installation.

**Comment by ravic-rs** [comment]
> fixed issues with testinstall in msys2 mingw64 env, and cleaned up msys2 ci steps. Now, it looks clean for msys2.
> 
> msvc build seems to be having issues, but looks unrelated to these changes, as it has been failing at the same place for previous few CI runs as well. (copying built tcl lib) - most likely the path from which the copy is being attempted is not valid, probably due to changes in the windows-2022 gh container msvc installation.

Can we plan to update build instructions for users within /docs in a separate issue?

That's my understanding too, we are watching that tcl lib CI failure closely.

**Comment by coolbreeze413** [comment]
@ravic-rs yes, we can do that. Do you want me to raise an issue for doc update, and then a separate PR for the changes?

**Comment by ravic-rs** [comment]
> @ravic-rs yes, we can do that. Do you want me to raise an issue for doc update, and then a separate PR for the changes?

Yes, that would be great! 

Regarding the commits, if we can squash them that will be easier to read for history later.

**Comment by coolbreeze413** [comment]
@ravic-rs : For the commits, as we keep the fork updated from this repo using merge commits (easier to merge newer changes as and when they happen from this repo to fork) it contains a lot of extra sync commits, and squashing at the fork causes issues with github not recognizing a cleaner history.
Once we decide to merge these changes, we can use a squash and merge so we can have a clean history here as well.

**Comment by ravic-rs** [comment]
> @ravic-rs : For the commits, as we keep the fork updated from this repo using merge commits (easier to merge newer changes as and when they happen from this repo to fork) it contains a lot of extra sync commits, and squashing at the fork causes issues with github not recognizing a cleaner history. Once we decide to merge these changes, we can use a squash and merge so we can have a clean history here as well.

Sounds good. I will squash them there.

**Comment by ravic-rs** [comment]
@coolbreeze413 could you please merge main into your branch ? For some reason, github doesn't allow me to merge the msvc compiler path fixes to this one.
image

**Comment by coolbreeze413** [comment]
@ravic-rs : I have rebased the changes with the latest from `main` - now it should be ok.

**Comment by ravic-rs** [comment]
> @ravic-rs : I have rebased the changes with the latest from `main` - now it should be ok.

Thank you! It's merged.

Follow up to this. https://github.com/os-fpga/FOEDAG/issues/597

**Pull request merged**
