### PR TITLE
[RG-225] Add Start with Simulation button

### PR DESCRIPTION
**Pull request by KochynVolodymyr**
### Motivate of the pull request
Provide user another compilation from with simulation.

### Describe the technical details
TaskManager has two option start compilation:
* Regular steps, like Analyze, synth, place...
* Regular with simulation.

Also every task now can be enabled and disabled. Disabled task will be grayed out and will not run.

 ### Which part of the code base require a change
 
 - [x] Library: compiler, foedagcore
 - [ ] Plug-in: <Specify the plugin name>
 - [ ] Engine
 - [ ] Documentation
 - [ ] Regression tests
 - [ ] Continous Integration (CI) scripts

### Screenshots
image
image

Disabled Simulate RTL:
image

### CODE REVIEW

**Comment by KochynVolodymyr** [comment]
> where did we get the new icon from ?
I did copy from existing and modified.

**Comment by ravic-rs** [comment]
> Also every task now can be enabled and disabled. Disabled task will be grayed out and will not run.

Thanks.

One more question, we only need enable/disable for simulation tasks. Other tasks doesn't need it because we define their availability based on the project type. Can you confirm ?
`Also every task now can be enabled and disabled. Disabled task will be grayed out and will not run.`

**Comment by ravic-rs** [comment]
> > where did we get the new icon from ?
> 
> I did copy from existing and modified.

I think the contrast if low for orange on green, do you think black color for text (SIM) will improve the contrast ?

**Comment by KochynVolodymyr** [comment]
> > > where did we get the new icon from ?
> > 
> > 
> > I did copy from existing and modified.
> 
> I think the contrast is low for orange on green, do you think black color for text (SIM) will improve the contrast ?

image

**Comment by alaindargelas** [comment]
Looks good to me, less colors the better

**Comment by ravic-rs** [comment]
> > > > where did we get the new icon from ?
> > > 
> > > 
> > > I did copy from existing and modified.
> > 
> > 
> > I think the contrast is low for orange on green, do you think black color for text (SIM) will improve the contrast ?
> 
> image

Looks good! Is the "Simulation" disabled intentionally in the context menu ? The simulation run button seems to be available so just want to be sure.

**Comment by KochynVolodymyr** [comment]
> > > > > where did we get the new icon from ?
> > > > 
> > > > 
> > > > I did copy from existing and modified.
> > > 
> > > 
> > > I think the contrast is low for orange on green, do you think black color for text (SIM) will improve the contrast ?
> > 
> > 
> > image
> 
> Looks good! Is the "Simulation" disabled intentionally in the context menu ? The simulation run button seems to be available so just want to be sure.

Yes. But I think we need to reconsider this. But maybe not in scope of this ticket.

**Review by ravic-rs — APPROVED** [review]
Looks good.

**Pull request merged**
