### PR TITLE
[RG-120] Fixed library and include paths

### PR DESCRIPTION
**Pull request by KochynVolodymyr**
### Motivate of the pull request
Solve issue with library and include path.

 ### Describe the technical details
In case we save path as ../<user define> we got a problem with Project settings and project file. So if we keep original path and just add ../ when we need this solve all problems.

 ### Which part of the code base require a change
 
 - [x] Library: compiler
 - [ ] Plug-in: <Specify the plugin name>
 - [ ] Engine
 - [ ] Documentation
 - [ ] Regression tests
 - [ ] Continous Integration (CI) scripts

### CODE REVIEW

**Comment by KochynVolodymyr** [comment]
@alain-rs need your opinion on this. This changes solve Project settings and project file issue with path. Otherwise we have to put some workaround for both cases.

**Comment by alaindargelas** [comment]
Looks good in principle, have you tried with the 
make test/batch   regression in Raptor to validate it does not break anything?

**Comment by KochynVolodymyr** [comment]
> Looks good in principle, have you tried with the make test/batch regression in Raptor to validate it does not break anything?

@alaindargelas Yes I tested. Everything passed.

**Review by ravic-rs — APPROVED** [review]
Looks good.

**Review by ravic-rs — CHANGES_REQUESTED** [review]
Merge on hold due to a include path issue with analyze command.

**Review by ravic-rs — APPROVED** [review]
Looks good.

**Pull request merged**
