### PR TITLE
Implement the user interface for mapping logical clocks to  fabric physical clock

### PR DESCRIPTION
**Pull request by umariqbal-rs**
> ### Motivate of the pull request
> - [ ] To address an existing issue. If so, please provide a link to the issue: <issue id>
> - [ ] Breaking new feature. If so, please describe details in the description part.

> ### Describe the technical details
Gemini device supports 16 different physical clock inputs to FPGA fabric. This allows user to have design with 16 different clocks. This mapping between physical to logical happens by providing repacker.xml file. All the related discussion is in attached link below
 [EDA-691](https://rapidsilicon.atlassian.net/browse/EDA-691).
> 
> 
> 
> 
> 
>
> #### What does this pull request change?
> 
> 
> 
> 
> 

> ### Which part of the code base require a change
> 
> - [ ] Library: <Specify the library name>
> - [ ] Plug-in: <Specify the plugin name>
> - [ ] Engine
> - [ ] Documentation
> - [ ] Regression tests
> - [ ] Continous Integration (CI) scripts

> ### Impact of the pull request

> - [ ] Require a change on Quality of Results (QoR)
> - [ ] Break back-compatibility. If so, please list who may be influenced.

[EDA-691]: https://rapidsilicon.atlassian.net/browse/EDA-691?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by alain-rs** [comment]
Let's keep in in Draft mode this week

**Comment by alain-rs** [comment]
@umariqbal-rs please fix code formatting

**Comment by umariqbal-rs** [comment]
@alain-rs 
This pull request is also ready. Can you please review and merge.

**Comment by alaindargelas** [comment]
@umariqbal-rs please see message from Github: This branch is out-of-date with the base branch
Please update your PR.

**Pull request merged**
