### PR TITLE
Fixed issue when all tasks are enabled when start post synth project from script

### PR DESCRIPTION
**Pull request by KochynVolodymyr**
### Motivate of the pull request
 - [x] To address an existing issue. If so, please provide a link to the issue: <issue id>
 - [ ] Breaking new feature. If so, please describe details in the description part.

 ### Describe the technical details
 If start post synth project from script, all tasks become available. But some of the tasks should be hidden.

 ### Which part of the code base require a change
 
 - [x] Library: foedagcore
 - [ ] Plug-in: <Specify the plugin name>
 - [ ] Engine
 - [ ] Documentation
 - [ ] Regression tests
 - [ ] Continous Integration (CI) scripts

### CODE REVIEW

**Comment by ravic-rs** [comment]
@KochynVolodymyr which script are we referring here ? I don't think we have a tcl script for PoS project in test cases.

**Comment by KochynVolodymyr** [comment]
> @KochynVolodymyr which script are we referring here ? I don't think we have a tcl script for PoS project in test cases.

Yes, we have

**Comment by ravic-rs** [comment]
Could you please point me to it in foedag ?

**Comment by KochynVolodymyr** [comment]
> Could you please point me to it in foedag ?

We have it upstream

**Review by ravic-rs — APPROVED** [review]

**Pull request merged**
