### PR TITLE
ChatGPT integration

### PR DESCRIPTION
**Pull request by KochynVolodymyr**
> ### Motivate of the pull request
> - [ ] To address an existing issue. If so, please provide a link to the issue: <issue id>
> - [ ] Breaking new feature. If so, please describe details in the description part.

> ### Describe the technical details
> #### What is currently done? (Provide issue link if applicable)
> 
> 
> 
> 
> 
>
> #### What does this pull request change?
> 
> 
> 
> 
> 

> ### Which part of the code base require a change
> 
> - [ ] Library: <Specify the library name>
> - [ ] Plug-in: <Specify the plugin name>
> - [ ] Engine
> - [ ] Documentation
> - [ ] Regression tests
> - [ ] Continous Integration (CI) scripts

> ### Impact of the pull request

> - [ ] Require a change on Quality of Results (QoR)
> - [ ] Break back-compatibility. If so, please list who may be influenced.

### CODE REVIEW

**Comment by KochynVolodymyr** [comment]
@ravic-rs I accidentally rewrite your changes. Could you please take a look?

**Comment by ravic-rs** [comment]
Closing this for re-work.

**Review by ravic-rs — CHANGES_REQUESTED** [review]
Pending for timeout at 3min and help for chatgpt commands.

**Comment by KochynVolodymyr** [comment]
> Pending for timeout at 3min and help for chatgpt commands.

This is done.

**Review by ravic-rs — APPROVED** [review]
Looks good, we need to move this into a submodule after this PR.
Also,
1. Preserve current ChatGPT history unless user resets in the session.
2. Open/Close ChatGPT view in editor using the View menu in toolbar.

**Pull request merged**
