### PR TITLE
Put tk library side to tcl

### PR DESCRIPTION
**Pull request by nadeemyaseen-rs**
To make FOEDAG generated TCL library to be used by GTKwave as well, putting the TK library parallel to TCL library

### CODE REVIEW

**Comment by ravic-rs** [comment]
@nadeemyaseen-rs do we know if the tcl library we have in foedag is compatible with the gtkwave version ? Did you test this with some testcase on Raptor ?

**Comment by nadeemyaseen-rs** [comment]
> @nadeemyaseen-rs do we know if the tcl library we have in foedag is compatible with the gtkwave version ? Did you test this with some testcase on Raptor ?

Yes, I have tested at the Raptor level with the test cases. and it is working.

**Comment by ravic-rs** [comment]
> > @nadeemyaseen-rs do we know if the tcl library we have in foedag is compatible with the gtkwave version ? Did you test this with some testcase on Raptor ?
> 
> Yes, I have tested at the Raptor level with the test cases. and it is working.

Please add the tcl library version to the description.

**Comment by nadeemyaseen-rs** [comment]
It’s same 8.6. The change is in directory structure only.

**Pull request merged**
