### PR TITLE
Add program_device help

### PR DESCRIPTION
**Pull request by guanyung-rs**
> ### Motivate of the pull request
> - [ ] To address an existing issue. If so, please provide a link to the issue: <issue id>
> - [ ] Breaking new feature. If so, please describe details in the description part.

Adding program_device help context
image

> ### Describe the technical details
> #### What is currently done? (Provide issue link if applicable)
> 
> 
> 
> 
> 
>
> #### What does this pull request change?
Compiler help description message, specifically for program_device
> 
> 
> 
> 
> 

> ### Which part of the code base require a change
> 
> - [ ] Library: <Specify the library name>
> - [ ] Plug-in: <Specify the plugin name>
> - [ ] Engine
> - [ ] Documentation
> - [ ] Regression tests
> - [ ] Continous Integration (CI) scripts

> ### Impact of the pull request

> - [ ] Require a change on Quality of Results (QoR)
> - [ ] Break back-compatibility. If so, please list who may be influenced.

### CODE REVIEW

**Review by ecchg — APPROVED** [review]

**Comment by KochynVolodymyr** [comment]
Please wait for https://github.com/os-fpga/FOEDAG/pull/1089

**Comment by guanyung-rs** [comment]
> Please wait for https://github.com/os-fpga/FOEDAG/pull/1089

Ok.

**Comment by ravic-rs** [comment]
> > Please wait for #1089
> 
> Ok.

@guanyung-rs we will add the program help text in this PR  #1089. Please update this PR to cleanup the code.

**Comment by guanyung-rs** [comment]
> > > Please wait for #1089
> > 
> > 
> > Ok.
> 
> @guanyung-rs we will add the program help text in this PR #1089. Please update this PR to cleanup the code.

@ravic-rs , Since PR #1089 will include the program help text, I am closing this PR. There is nothing else to clean up other than I posted this PR #1094 to fix the program_device --help text

**Pull request closed without merging**
