### PR TITLE
[RG-481] Revert default parser if it was switched during analysis or synthesis

### PR DESCRIPTION
**Pull request by KochynVolodymyr**
### Motivate of the pull request
 - [x] To address an existing issue. If so, please provide a link to the issue: RG-481
 - [ ] Breaking new feature. If so, please describe details in the description part.

### Describe the technical details
We try to run analyze and synthesis second time when default parser failed. For the second try we change default parser to surelog. We need to return back previous parser when analysis or synthesis operations done. Otherwise user have to run tcl command in order to setup parser they need.  

Additionally, added save cmd (analysis) and ys (synth) files from previous step which failed. 

 ### Which part of the code base require a change
 
 - [x] Library: compiler
 - [ ] Plug-in: <Specify the plugin name>
 - [ ] Engine
 - [ ] Documentation
 - [ ] Regression tests
 - [ ] Continous Integration (CI) scripts

### CODE REVIEW

**Comment by alain-rs** [comment]
@KochynVolodymyr , when the switch from default parser to Surelog happens, it is **irrevocable**. The entire tool flow is now switched to the new parser.
There is **no point** in trying again the default parser or reverting.
I don't understand what is attempted in this PR.

**Review by alain-rs — CHANGES_REQUESTED** [review]
@KochynVolodymyr , when the switch from default parser to Surelog happens, it is irrevocable. The entire tool flow is now switched to the new parser.
There is no point in trying again the default parser or reverting. Basically the tool overrides the user parser wish.

I don't understand what is attempted in this PR.

**Comment by KochynVolodymyr** [comment]
@alain-rs What if user did some mistake, e.g. forgot add some file or selected wrong file. Then they fixed that problem but parser already switched. That's very weird behavior. Please close this PR if this is expected.

**Comment by alain-rs** [comment]
Yes, it is expected. Closing this.

**Pull request closed without merging**
