### PR TITLE
Detecting bit overlap for attributes within a block

### PR DESCRIPTION
**Pull request by manadher**
> ### Motivate of the pull request
> - Detecting Configuration memory space overlap

### CODE REVIEW

**Review by alaindargelas — APPROVED** [review]

**Comment by alaindargelas** [comment]
@manadher This PR does not address the problem:

INFO: BIT: Top Modules: and2

ERROR: BIT: Assertion at Configuration/ModelConfig/ModelConfig.cpp (func: add_bitfield, line: 624)
ERROR: BIT:   MSG: (mask[j >> 3] & (1 << (j & 7))) == 0
ERROR: BIT: Fail to execute command: model_config
ERROR: BIT: Design and2 IO bitstream generation failed
Fail to execute command: model_config
    while executing
"model_config set_model -feature IO PERIPHERY"
    (file "and2_io_bitstream_cmd.tcl" line 7)
    invoked from within
"source and2_io_bitstream_cmd.tcl"
    invoked from within
"bitstream "
    (file "tests/Testcases/and2_verilog/run_raptor.tcl" line 52)

**Comment by manadher** [comment]
@alaindargelas This feature does not fix the RIC model overlapping bits. It detects them at compilation. So, if someone writes overlapping attributes and tries to compile them with the RIC compiler , the ric compiler will fail and indicate the command/file/line of the attempt to overwrite a certain bit.

**Comment by manadher** [comment]
Here's the task as you, yourself, described it in the Jira case [2853](https://rapidsilicon.atlassian.net/browse/EDA-2853)
@Manadher Kharroubi is going to make a change in the C++ RIC modeler code tomorrow to avoid address overlap, that change will go in build 1.0.55 and you will get that build the day after

**Comment by alaindargelas** [comment]
Correct the code has to make the bits not overlapping by construction, not by checking

**Comment by ravikiranchollangi** [comment]
@manadher codeformatting and ubuntu tests are failing with this PR. 
image

**Comment by ravikiranchollangi** [comment]
> @manadher codeformatting and ubuntu tests are failing with this PR. image

Ubuntu one seems to be a false positive CI failure but code formatting is still an issue.
image

**Pull request merged**
