### PR TITLE
Enhancement on Configuration subsystem

### PR DESCRIPTION
**Pull request by chungshien**
> ### Motivate of the pull request
> - [x] To address an existing issue. If so, please provide a link to the issue: <issue id>
> - [ ] Breaking new feature. If so, please describe details in the description part.

> ### Describe the technical details
Enhancement to CFGArg. 
1. Support "hide" property
2. Change the class internal variable to be big cap for the 1st char, then argument option can be named freely (except help)

> #### What is currently done? (Provide issue link if applicable)
> 
> 
> 
> 
> 
>
> #### What does this pull request change?
> 
> 
> 
> 
> 

> ### Which part of the code base require a change
> 
> - [ ] Library: <Specify the library name>
> - [ ] Plug-in: <Specify the plugin name>
> - [x] Engine
> - [ ] Documentation
> - [ ] Regression tests
> - [ ] Continous Integration (CI) scripts

> ### Impact of the pull request

> - [ ] Require a change on Quality of Results (QoR)
> - [ ] Break back-compatibility. If so, please list who may be influenced.

### CODE REVIEW

**Comment by ravic-rs** [comment]
@guanyung-rs please use descriptive title for PRs that are searchable in future or available in changelog text.

**Comment by chungshien** [comment]
> Please keep the class variable names consistent with other parts of the code. You can refer compiler.cpp for e.g. https://github.com/os-fpga/FOEDAG/blob/main/src/Compiler/Compiler.cpp

@alain-rs 

I will change this round. But in general I do not agree if one subsystem names the member in one way, then all subsystem need to follow the naming scheme. It should depend on the nature of the work. 

Configuration dealing with a lot of bitfield, register level 

If I am going to create member (class or structure) I would like to name it accordingly to SPEC. For example access the bitfield as: pcb.pl_ctl.enable, which is the standard practice. 

If we follow the naming used by other subsystem which add "m_" at front, then it will become pcb.m_pl_ctl.m_enable (this is not common practice, this make the code messy when cross check with SPEC)

image

**Comment by alaindargelas** [comment]
Yes, please follow the spec naming convention for those fields.

**Comment by ravic-rs** [comment]
> > Please keep the class variable names consistent with other parts of the code. You can refer compiler.cpp for e.g. https://github.com/os-fpga/FOEDAG/blob/main/src/Compiler/Compiler.cpp
> 
> @alain-rs
> 
> I will change this round. But in general I do not agree if one subsystem names the member in one way, then all subsystem need to follow the naming scheme. It should depend on the nature of the work.
> 
> Configuration dealing with a lot of bitfield, register level
> 
> If I am going to create member (class or structure) I would like to name it accordingly to SPEC. For example access the bitfield as: pcb.pl_ctl.enable, which is the standard practice.
> 
> If we follow the naming used by other subsystem which add "m_" at front, then it will become pcb.m_pl_ctl.m_enable (this is not common practice, this make the code messy when cross check with SPEC)
> 
> image

Thanks. This background is useful to understand the reason behind your proposed changes. These can go into the description to help reviewers in future for deviations.

**Review by ravic-rs — APPROVED** [review]

**Pull request merged**
