### PR TITLE
Allow user to stop programming process

### PR DESCRIPTION
**Pull request by KochynVolodymyr**
### Motivate of the pull request
 - [ ] To address an existing issue. If so, please provide a link to the issue: <issue id>
 - [x] Breaking new feature. If so, please describe details in the description part.

 ### Describe the technical details
Implement Stop functionality. 
Change Pause button to Stop.
image

 ### Which part of the code base require a change
 
 - [x] Library: programmer-gui
 - [ ] Plug-in: <Specify the plugin name>
 - [ ] Engine
 - [ ] Documentation
 - [ ] Regression tests
 - [ ] Continous Integration (CI) scripts

### CODE REVIEW

**Review by guanyung-rs — APPROVED** [review]
The change looks good to me. The stop logic to link to the ProgramFPGA API is correct.

**Comment by guanyung-rs** [comment]
This is tested in the emulator. The stop works as expected
image

**Comment by ravic-rs** [comment]
> This is tested in the emulator. The stop works as expected image

@guanyung-rs do we need to do any clean-up once the process is stopped? It should happen in the backend itself if we have unnecessary or previously generated files.

**Review by ravic-rs — APPROVED** [review]

**Comment by guanyung-rs** [comment]
@ravic-rs 
There is no file is generated or anything to clean-up. The clean up process is delegated to the openocd logic and firmware level.

**Pull request merged**
