### PR TITLE
[RG-227] Add simulation options to Project settings

### PR DESCRIPTION
**Pull request by KochynVolodymyr**
### Motivate of the pull request
Add top module name for simulation and all other option as Design source page have.

### Describe the technical details
Simulation top module was moved from Simulation (`Simulator::SetSimulationTop`) to Project manager (`ProjectManager::setTopModuleSim`)
This change required because now simulation top module could be set from tcl command and GUI.

 ### Which part of the code base require a change
 
 - [x] Library: simulation, newproject
 - [ ] Plug-in: <Specify the plugin name>
 - [ ] Engine
 - [ ] Documentation
 - [ ] Regression tests
 - [ ] Continous Integration (CI) scripts

### Screenshots
image

### CODE REVIEW

**Comment by ravic-rs** [comment]
@alain-rs should we leave the same file path options in Simulation Files view as the Design Files view ?

image

**Review by ravic-rs — CHANGES_REQUESTED** [review]
How can we verify that "set_top_testbench" has the same behavior with the GUI counterpart ?

**Comment by KochynVolodymyr** [comment]
> How can we verify that "set_top_testbench" has the same behavior with the GUI counterpart ?

We have simulation test project.

**Comment by ravic-rs** [comment]
> > How can we verify that "set_top_testbench" has the same behavior with the GUI counterpart ?
> 
> We have simulation test project.

Could you point me to it ? I see only tcl ones.

**Comment by ravic-rs** [comment]
We also need Library and Compilation unit like the Design Files option.

**Comment by ravic-rs** [comment]
> > > How can we verify that "set_top_testbench" has the same behavior with the GUI counterpart ?
> > 
> > 
> > We have simulation test project.
> 
> Could you point me to it ? I see only tcl ones.

We can run a project using the --project flag.

**Comment by alaindargelas** [comment]
In Raptor a good test would be: tests/Testcases/oneff/raptor.tcl

**Review by ravic-rs — APPROVED** [review]

**Pull request merged**
