### PR TITLE
Foedag config

### PR DESCRIPTION
**Pull request by chungshien**
> ### Motivate of the pull request
> - [ ] To address an existing issue. If so, please provide a link to the issue: <issue id>
> - [x] Breaking new feature. If so, please describe details in the description part.

> ### Describe the technical details
Adding new configuration module for configuration team. Configuration team will eventually owns few core feature (I call them submodules here): bitstream assembler, bitstream generator, device programming and etc. Instead of each submodules defined under "src", the code structure of configuration module would be:
--> src
------> other modules (example: Compiler, PinAssignment etc)
------> Configuration module
----------> configuration submodule 1
----------> configuration submodule 2
----------> etc

Currently adding 3 configuration submodule
(1) CFGCommon -- common code (helper APIs) that will be shared among all the configuration submodule
(2) CFGCompiler -- this is the interface that will interact with outside world (FOEDAG UI). This submodule will link none-config-core-feature library like TCL, QT
(3) Programmer -- this is reference to develop more core-feature-submodule. Currently it only has dummy function. It only needs to link the necessary library for core-feature development. All unnecessary libraries (for example TCL, QT) is not needed (CFGCompiler will handle that). This way configuration core-feature will have a very clean library dependency and clean standalone executable 

More detail is on https://rapidsilicon2-my.sharepoint.com/:o:/g/personal/chungshien_chai_rapidsilicon_com/EnhKjsIQ1Y1MgwPuahLuyOsBka_EqaODN3oTkCAEGzumJQ?e=goO1lE (page: Configuration Structure in FOEDAG/FOEDAG_rs, only accessible by RS people)

> #### What is currently done? (Provide issue link if applicable)
> 
> 
> 
> 
> 
>
> #### What does this pull request change?
> 
> 
> 
> 
> 

> ### Which part of the code base require a change
> 
> - [ ] Library: <Specify the library name>
> - [ ] Plug-in: <Specify the plugin name>
> - [x] Engine
> - [ ] Documentation
> - [ ] Regression tests
> - [ ] Continous Integration (CI) scripts

> ### Impact of the pull request

> - [ ] Require a change on Quality of Results (QoR)
> - [ ] Break back-compatibility. If so, please list who may be influenced.

### CODE REVIEW

**Comment by alain-rs** [comment]
tests/TestInstall/ CMake needs to be updated with the new library.

**Comment by chungshien** [comment]
> tests/TestInstall/ CMake needs to be updated with the new library.

Yes I noticed that TestInstall is failing, but I already added all 3 newly generated libraries into TestInstall CMake. Locally when I "ld" the .a library I do not see any issue. I will need to spend some time to look at what git CI flow is really doing. 

Will continue the debug later tonight or tomorrow.

**Comment by alain-rs** [comment]
To test locally you have to run:

sudo make install
sudo make test_install

**Comment by chungshien** [comment]
> To test locally you have to run:
> 
> sudo make install sudo make test_install

**Comment by chungshien** [comment]
> > tests/TestInstall/ CMake needs to be updated with the new library.
> 
> Yes I noticed that TestInstall is failing, but I already added all 3 newly generated libraries into TestInstall CMake. Locally when I "ld" the .a library I do not see any issue. I will need to spend some time to look at what git CI flow is really doing.
> 
> Will continue the debug later tonight or tomorrow.

Figure the rootcause, the ordering is important - see https://github.com/os-fpga/FOEDAG/commit/483246ec4292d52fea5e001518d21c4280f80014

**Review by ecchg — APPROVED** [review]

**Pull request merged**
