### PR TITLE
Build stable MSVC compiler path for windows-msvc GH CI action 

### PR DESCRIPTION
**Pull request by ravic-rs**
> ### Motivate of the pull request
> - [x] To address an existing issue. If so, please provide a link to the issue: #596 
Previous temp fix #595 
> - [ ] Breaking new feature. If so, please describe details in the description part.

> ### Describe the technical details
> #### What is currently done? (Provide issue link if applicable)
1. PROCESSOR_ARCHITECTURE: https://docs.microsoft.com/en-us/windows/win32/winprog64/wow64-implementation-details
- Within CMake: https://cmake.org/cmake/help/v3.13/variable/CMAKE_HOST_SYSTEM_PROCESSOR.html#variable:CMAKE_HOST_SYSTEM_PROCESSOR
2. _MSC_VER: https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=msvc-170
- Current MSVC version 1933: https://en.wikipedia.org/wiki/Microsoft_Visual_C%2B%2B
- Within CMake MSVC version is accessible using: https://cmake.org/cmake/help/latest/variable/MSVC_VERSION.html
3. How TCL generates the build the output directory: https://github.com/os-fpga/FOEDAG/blob/720232079a5a34071903e0ff37f206a5fb0a78e2/third_party/tcl8.6.12/win/rules.vc#L1040
- https://github.com/os-fpga/FOEDAG/blob/720232079a5a34071903e0ff37f206a5fb0a78e2/third_party/tcl8.6.12/win/rules.vc#L1063
4.  **Best solution would be to expose this to Cmakelists using a env variable and extract what we need. But that would mean a lot of refactoring to paths**
5. Refer the following for details information on tcl build rationale: https://core.tcl-lang.org/tips/doc/main/tip/477.md

> #### What does this pull request change?
> windows-msvc build path

> ### Which part of the code base require a change
> - [ ] Library: <Specify the library name>
> - [ ] Plug-in: <Specify the plugin name>
> - [ ] Engine
> - [ ] Documentation
> - [ ] Regression tests
> - [x] Continous Integration (CI) scripts

> ### Impact of the pull request

> - [ ] Require a change on Quality of Results (QoR)
> - [ ] Break back-compatibility. If so, please list who may be influenced.

### CODE REVIEW

**Comment by ravic-rs** [comment]
@alain-rs curious to know why we didn't bring the tcl as a submodule.
https://github.com/os-fpga/FOEDAG/tree/main/third_party/tcl8.6.12

**Comment by alaindargelas** [comment]
Tcl changes too often with sometime incompatible changes, typically EDA tools stay years on the same Tcl version without updating.

**Comment by ravic-rs** [comment]
> Tcl changes too often with sometime incompatible changes, typically EDA tools stay years on the same Tcl version without updating.

If you don't have any concerns, I will go ahead and merge this one.

**Comment by alaindargelas** [comment]
Yes please do.

**Pull request merged**
