### PR TITLE
[EDA-957] Initial implementation of Compute Usage  table which shows task duration and memory utilization

### PR DESCRIPTION
**Pull request by KochynVolodymyr**
### Motivate of the pull request
 - [ ] To address an existing issue. If so, please provide a link to the issue: <issue id>
 - [x] Breaking new feature. If so, please describe details in the description part.

### Describe the technical details
Add new feature - Compute Usage:
image

Result is available only after task successfully done.
 
Result is N/A in case:
* Task was cleaned
* Task was skipped because of no design change.
* Project was opened.

For simulation task:
* Duration is a sum of three (elaboration, compile and simulate)
* Utilization is maximum of three  (elaboration, compile and simulate)

 ### Which part of the code base require a change
 
 - [x] Library: compiler, foedagcore
 - [ ] Plug-in: <Specify the plugin name>
 - [ ] Engine
 - [ ] Documentation
 - [ ] Regression tests
 - [ ] Continous Integration (CI) scripts

### CODE REVIEW

**Comment by ravic-rs** [comment]
image

**Comment by ravic-rs** [comment]
Add "Why we don't have this for simulation tasks" to the description.

**Comment by alain-rs** [comment]
@ravic-rs This should not be called "Performance", it is misleading. The Performance of an FPGA is its Fmax.
This should be called "Compute usage" or something like that

**Comment by ravic-rs** [comment]
> @ravic-rs This should not be called "Performance", it is misleading. The Performance of an FPGA is its Fmax. This should be called "Compute usage" or something like that

@alain-rs the term's coming from "perf.log". Is "Compilation Performance" better? Let us know else we will go with "Compute Usage".

**Comment by alain-rs** [comment]
Let's go for Compute usage.

**Pull request merged**
