### PR TITLE
IO bitstream generation

### PR DESCRIPTION
**Pull request by chungshien-chai**
> ### Motivate of the pull request
> - [ ] To address an existing issue. If so, please provide a link to the issue: <issue id>
> - [x] Breaking new feature. If so, please describe details in the description part.

> ### Describe the technical details
> #### What is currently done? (Provide issue link if applicable)
Changes include:
a. Provide API to validate parameter(s) before using it. (Use case: for example PLL need to validate the multiply and division params)
b. Prepare to support clock routing to gearbox. In the progress understanding RTL what to set in bits to support. 

Testing:
a. ported code (together with https://github.com/os-fpga/yosys_verific_rs/pull/626) to latest NS Raptor manually
b. run batch, batch_gen2 and batch_gen3 test.

>
> #### What does this pull request change?
> 
> 
> 
> 
> 

> ### Which part of the code base require a change
> 
> - [ ] Library: <Specify the library name>
> - [ ] Plug-in: <Specify the plugin name>
> - [ ] Engine
> - [ ] Documentation
> - [ ] Regression tests
> - [ ] Continous Integration (CI) scripts

> ### Impact of the pull request

> - [ ] Require a change on Quality of Results (QoR)
> - [ ] Break back-compatibility. If so, please list who may be influenced.

### CODE REVIEW

**Comment by chungshien-chai** [comment]
@NadeemYaseen , all macos failed because of python version - https://github.com/os-fpga/FOEDAG/actions/runs/8823274431/job/24223371267?pr=1548. But my changes does not change anything on workflows.

**Comment by alaindargelas** [comment]
Need to resolve the MacOS failures before merge

**Comment by ravikiranchollangi** [comment]
> @NadeemYaseen , all macos failed because of python version - https://github.com/os-fpga/FOEDAG/actions/runs/8823274431/job/24223371267?pr=1548. But my changes does not change anything on workflows. 

It's related to Python version support in latest macOS on CI. Unless @nadeemyaseen-rs has a solution to use the version we need, we should pin the macOS to previous one for time being.

**Comment by NadeemYaseen** [comment]
This https://github.com/os-fpga/FOEDAG/pull/1549 will hopefully fix the MacOS issue

**Pull request merged**
