### PR TITLE
Issue 147 terminate command

### LINKED ISSUE #147: Terminate command running.
Add possibility to terminate running of current command with combination Ctrl+C when there is no text selection.

### PR DESCRIPTION
**Pull request by KochynVolodymyr**
Close #147

### CODE REVIEW

**Review by alaindargelas — COMMENTED** [review]
Please keep the Google style.

**Comment by KochynVolodymyr** [comment]
I'm keeping google style.
inside the file we have:

BasedOnStyle: Google

**Comment by alaindargelas** [comment]
I see some files have changed their format.
Please keep it as the command line argument of clang-format

**Comment by KochynVolodymyr** [comment]
> I see some files have changed their format. Please keep it as the command line argument of clang-format

please show which one. For me looks good.

**Comment by alaindargelas** [comment]
Hard to tell because there is code change too.
Please do not make multi-purpose change lists.
A changelist should be for one purpose only.
If there is a change of format needed that should be submitted in its own change list, not mixed with code changes.
Please remove that change of format technique from this particular change list and submit a different changelist with the change of format technique (Which I still don't understand why you need to change that).

**Comment by alain-rs** [comment]
Simply revert the change from Google to file and put back the Google setting.
I won't accept the changelist.

Alain Dargelas, Ph.D.
Vice President EDA Software
RapidSilicon
________________________________

**Pull request closed without merging**
