### PR TITLE
Add tcl console to programmer

### PR DESCRIPTION
**Pull request by KochynVolodymyr**
### Motivate of the pull request
 - [ ] To address an existing issue. If so, please provide a link to the issue: <issue id>
 - [x] Breaking new feature. If so, please describe details in the description part.

 ### Describe the technical details
Add tcl console support in programmer 
image

 ### Which part of the code base require a change
 
 - [x] Library: programmer-gui
 - [ ] Plug-in: <Specify the plugin name>
 - [ ] Engine
 - [ ] Documentation
 - [ ] Regression tests
 - [ ] Continous Integration (CI) scripts

### CODE REVIEW

**Comment by ravic-rs** [comment]
@guanyung-rs @nadeemyaseen-rs FYI, adding this means when we release this programmer as a standalone app then we will have to bundle the tcl submodule as well.

**Review by ravic-rs — CHANGES_REQUESTED** [review]
Please remove the non-programmer GUI code (project manager).

**Comment by KochynVolodymyr** [comment]
> Please remove the non-programmer GUI code (project manager).

This required more changes. Maybe another PR?

**Comment by KochynVolodymyr** [comment]
> Please remove the non-programmer GUI code (project manager).

Done

**Pull request merged**
