### PR TITLE
[GEMINIEDA-480] Save IP Instance info to project file

### PR DESCRIPTION
**Pull request by skyler-rs**
> ### Motivate of the pull request
> - [x] To address an existing issue. If so, please provide a link to the issue: [GEMINIEDA-480]
> - [ ] Breaking new feature. If so, please describe details in the description part.

> ### Describe the technical details
> #### What is currently done? (Provide issue link if applicable)
> Saving IP Instances was planned for december release and hadn't been written
>
> #### What does this pull request change?
> IP Instance config commands are now stored in the project so they can be re-configured at load time

> ### Which part of the code base require a change
> 
> - [x] Library: IpConfigurator, Main, MainWindow, NewProject
> - [ ] Plug-in: <Specify the plugin name>
> - [ ] Engine
> - [ ] Documentation
> - [ ] Regression tests
> - [ ] Continous Integration (CI) scripts

> ### Testing
> - Manually Tested in Foedag and Raptor

### CODE REVIEW

**Comment by ravic-rs** [comment]
@skyler-rs did we verify other settings feature upstream ?

**Comment by skyler-rs** [comment]
> @skyler-rs did we verify other settings feature upstream ?

Can you explain the question? What other settings are you referring to and what needs to be verified?

**Comment by ravic-rs** [comment]
> > @skyler-rs did we verify other settings feature upstream ?
> 
> Can you explain the question? What other settings are you referring to and what needs to be verified?

Settings has few functionalities like:
Making changes to existing project's design files, device selection, etc... 
Closing the modified project and re-opening to ensure the previous settings persists.
Basically sanity checks other than checking the IP instances persists when closed.

**Comment by skyler-rs** [comment]
Nope, just tested the saving/restoring. Ip has its own configuration object so I wasn't thinking about if other settings could somehow nuke mine, don't know if it's possible without looking at the code. I'll test that tomorrow morning.

**Comment by ravic-rs** [comment]
> Nope, just tested the saving/restoring. Ip has its own configuration object so I wasn't thinking about if other settings could somehow nuke mine, don't know if it's possible without looking at the code. I'll test that tomorrow morning. 

Cool, let's do sanity checks just to be sure.

**Comment by skyler-rs** [comment]
@ravic-rs I've confirmed that other settings don't affect the IP config settings. While testing that I remembered that i hadn't updated the "Remove IP" action in the source tree to update the project as well. I've added that in the latest commit.

**Pull request merged**
