### PR TITLE
[RG-139] Pin planner update, add Mode column

### PR DESCRIPTION
**Pull request by KochynVolodymyr**
### Motivate of the pull request
Add mode column for Package pin table in pin planner

### Which part of the code base require a change

- [x] Library: pinassignment
- [ ] Plug-in: <Specify the plugin name>
- [ ] Engine
- [ ] Documentation
- [x] Regression tests
- [ ] Continous Integration (CI) scripts

### Screenshots
image

### CODE REVIEW

**Comment by KochynVolodymyr** [comment]
@taoli4rs please take a look at the screenshot. This is how it looks like.

**Review by skyler-rs — APPROVED** [review]
Looks good, only thing that looks a bit odd is the hardcoding of the column number in the json (just prone to update mistakes if anything is added etc).

Since you're reading the json using an ordered format (`using json = nlohmann::ordered_json`), you could probably just increment columnId on each read and make it dynamic. 

That said, i can see how including it might provide a bit more portability incase some other system read the json in and wasn't doing it ordered.

No changes needed, just something to consider next time you're working with this code.

**Comment by KochynVolodymyr** [comment]
> Looks good, only thing that looks a bit odd is the hardcoding of the column number in the json (just prone to update mistakes if anything is added etc).
> 
> Since you're reading the json using an ordered format (`using json = nlohmann::ordered_json`), you could probably just increment columnId on each read and make it dynamic.
> 
> That said, i can see how including it might provide a bit more portability incase some other system read the json in and wasn't doing it ordered.
> 
> No changes needed, just something to consider next time you're working with this code.

I don't want rely on reading order. It is less obvious.

**Comment by taoli4rs** [comment]
> 
Layout LGTM. One question: when list of available modes for user to select, do we consider the port direction? Here in the screen shot, if design port "ct_vld" is input, then we should list modes of "Mode_XXXX_RX" only; similarly, if "ct_vld" is output, then we should list modes of "Mode_XXXX_TX" only.

**Comment by KochynVolodymyr** [comment]
> @volodymyrkochyn > Layout LGTM. One question: when list of available modes for user to select, do we consider the port direction? Here in the screen shot, if design port "ct_vld" is input, then we should list modes of "Mode_XXXX_RX" only; similarly, if "ct_vld" is output, then we should list modes of "Mode_XXXX_TX" only.

I'm on it.

**Comment by KochynVolodymyr** [comment]
@ravic-rs I guess this is ready

**Review by ravic-rs — APPROVED** [review]
Looks good.

**Comment by taoli4rs** [comment]
LGTM. We can do more enhancement later.

**Pull request merged**
